---
title: "git_00"
author: "Filipe"
date: "September 12, 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Girt with a boyish garb for boyish task,     
   Eager she wields her spade: yet loves as well       
Rest on the friendly knee, intent to ask     
         The tale one loves to tell.     
Rude scoffer of the seething outer strife,     

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,   
And sorry I could not travel both    
And be one traveler, long I stood     
And looked down one as far as I could     
To where it bent in the undergrowth;     

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,      
      Shining with all his might:    

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->


The grey sea and the long black land;      
And the yellow half-moon large and low;   
And the startled little waves that leap     
In fiery ringlets from their sleep,      
As I gain the cove with pushing prow,     
And quench its speed i' the slushy sand.      


Then a mile of warm sea-scented beach;     
Three fields to cross till a farm appears;      
A tap at the pane, the quick sharp scratch    
And blue spurt of a lighted match,      
And a voice less loud, thro' its joys and fears,    
Than the two hearts beating each to each!      
